name: Update Data

on:
  schedule:
    - cron: "0 */6 * * *"   # tiap 6 jam
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install requests beautifulsoup4

      - run: python generate.py

      - name: Commit & Push
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add data.json
          git commit -m "update data" || echo "no change"
          git push
